/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
/**
 *
 * @author Enzo-PC
 */
public class viewMenu extends javax.swing.JFrame {
    
    viewAltaPaciente vAlta = new viewAltaPaciente();
    viewAltaDieta vDieta = new viewAltaDieta();
    viewAltaComida vComida = new viewAltaComida();
    
    /**
     * Creates new form viewMenu
     */
    
    public viewMenu() {
        initComponents();
        vAlta.setSize(500, 300);
        vAlta.setLocation(0, 0);
        vDieta.setSize(500, 300);
        vDieta.setLocation(0, 0);
        vComida.setSize(500, 300);
        vComida.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAltaPacienteView = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAltaDietasView = new javax.swing.JButton();
        btnHomeView = new javax.swing.JButton();
        btnAltaComidas1 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        JpanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUTRICION ULP");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAltaPacienteView.setBackground(new java.awt.Color(255, 255, 255));
        btnAltaPacienteView.setFont(new java.awt.Font("Frank Ruhl Hofshi", 0, 36)); // NOI18N
        btnAltaPacienteView.setForeground(new java.awt.Color(89, 116, 146));
        btnAltaPacienteView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Avatar.png"))); // NOI18N
        btnAltaPacienteView.setText("PACIENTES");
        btnAltaPacienteView.setBorder(null);
        btnAltaPacienteView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltaPacienteViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltaPacienteViewMouseExited(evt);
            }
        });
        btnAltaPacienteView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaPacienteViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltaPacienteView, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 10, 290, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(89, 116, 146));
        jLabel4.setText(" NUTRICION ULP");
        jLabel4.setName(""); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 160, 30));

        btnAltaDietasView.setBackground(new java.awt.Color(255, 255, 255));
        btnAltaDietasView.setFont(new java.awt.Font("Frank Ruhl Hofshi", 0, 36)); // NOI18N
        btnAltaDietasView.setForeground(new java.awt.Color(89, 116, 146));
        btnAltaDietasView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dieta_logo.png"))); // NOI18N
        btnAltaDietasView.setText("DIETAS");
        btnAltaDietasView.setBorder(null);
        btnAltaDietasView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltaDietasViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltaDietasViewMouseExited(evt);
            }
        });
        btnAltaDietasView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaDietasViewActionPerformed(evt);
            }
        });
        jPanel2.add(btnAltaDietasView, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 240, 80));

        btnHomeView.setBackground(new java.awt.Color(255, 255, 255));
        btnHomeView.setForeground(new java.awt.Color(255, 255, 255));
        btnHomeView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home button.png"))); // NOI18N
        btnHomeView.setBorder(null);
        btnHomeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeViewActionPerformed(evt);
            }
        });
        jPanel2.add(btnHomeView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        btnAltaComidas1.setBackground(new java.awt.Color(255, 255, 255));
        btnAltaComidas1.setFont(new java.awt.Font("Frank Ruhl Hofshi", 0, 36)); // NOI18N
        btnAltaComidas1.setForeground(new java.awt.Color(89, 116, 146));
        btnAltaComidas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon_vegetables (1).png"))); // NOI18N
        btnAltaComidas1.setText("COMIDAS");
        btnAltaComidas1.setBorder(null);
        btnAltaComidas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltaComidas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltaComidas1MouseExited(evt);
            }
        });
        btnAltaComidas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaComidas1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAltaComidas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 250, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        content.setBackground(new java.awt.Color(89, 116, 146));
        content.setLayout(new java.awt.BorderLayout());

        JpanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo Menu.jpg"))); // NOI18N
        JpanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 640));

        content.add(JpanelMenu, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1280, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaPacienteViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaPacienteViewActionPerformed
        content.removeAll();
        content.add(vAlta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAltaPacienteViewActionPerformed

    private void btnAltaPacienteViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaPacienteViewMouseEntered
        btnAltaPacienteView.setBackground(new Color(102,174,192));
    }//GEN-LAST:event_btnAltaPacienteViewMouseEntered

    private void btnAltaPacienteViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaPacienteViewMouseExited
        btnAltaPacienteView.setBackground(Color.white);
    }//GEN-LAST:event_btnAltaPacienteViewMouseExited

    private void btnAltaDietasViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaDietasViewActionPerformed
        content.removeAll();
        content.add(vDieta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAltaDietasViewActionPerformed

    private void btnHomeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeViewActionPerformed
        content.removeAll();
        content.add(JpanelMenu, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnHomeViewActionPerformed

    private void btnAltaComidas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaComidas1ActionPerformed
        content.removeAll();
        content.add(vComida, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAltaComidas1ActionPerformed

    private void btnAltaDietasViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaDietasViewMouseEntered
        btnAltaDietasView.setBackground(new Color(102,174,192));
    }//GEN-LAST:event_btnAltaDietasViewMouseEntered

    private void btnAltaDietasViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaDietasViewMouseExited
        btnAltaDietasView.setBackground(Color.white);
    }//GEN-LAST:event_btnAltaDietasViewMouseExited

    private void btnAltaComidas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaComidas1MouseEntered
        btnAltaComidas1.setBackground(new Color(102,174,192));
    }//GEN-LAST:event_btnAltaComidas1MouseEntered

    private void btnAltaComidas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaComidas1MouseExited
        btnAltaComidas1.setBackground(Color.white);
    }//GEN-LAST:event_btnAltaComidas1MouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelMenu;
    private javax.swing.JButton btnAltaComidas1;
    private javax.swing.JButton btnAltaDietasView;
    private javax.swing.JButton btnAltaPacienteView;
    private javax.swing.JButton btnHomeView;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
