/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import AccesoADatos.ComidaData;
import AccesoADatos.DietaComidaData;
import AccesoADatos.DietaData;
import AccesoADatos.PacienteData;
import entidades.Comida;
import entidades.Dieta;
import entidades.DietaComida;
import entidades.Horario;
import entidades.Paciente;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo-PC
 */
public class viewAltaDieta extends javax.swing.JPanel {
    PacienteData pacienteData = new PacienteData();
    DietaData dietaData = new DietaData();
    ComidaData comidaData = new ComidaData();
    ArrayList<Paciente> pacientes = new ArrayList();
    ArrayList<Comida> comidas = new ArrayList<>();
    DietaComidaData dietaComidaData = new DietaComidaData();
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) { 
            return false;
        }   
    };
    ArrayList<Dieta> dietas;
    
    public viewAltaDieta() {
        initComponents();
        Border bordeInferior = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
        txtNombre.setBorder(bordeInferior);
        txtPesoIn.setBorder(bordeInferior);
        txtPesoIn.setEditable(false);
        cargarDatos();
        armarTabla();
        cargarDietas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBPacientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPesoIn = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        CFechaFin = new com.toedter.calendar.JDateChooser();
        CFechaIn = new com.toedter.calendar.JDateChooser();
        btnAlta = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        CBAlmuerzo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CBSnack = new javax.swing.JComboBox<>();
        CBDesayuno = new javax.swing.JComboBox<>();
        CBMerienda = new javax.swing.JComboBox<>();
        CBCena = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDietas = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 116, 146));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Alta de Dieta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccionar Paciente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        CBPacientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CBPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Paciente" }));
        CBPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(CBPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre de la Dieta: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de Inicio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha de Fin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Peso Inicial: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        txtPesoIn.setBackground(new java.awt.Color(89, 116, 146));
        txtPesoIn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPesoIn.setForeground(new java.awt.Color(0, 0, 0));
        txtPesoIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPesoIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 90, 40));

        txtNombre.setBackground(new java.awt.Color(89, 116, 146));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 40));

        CFechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(CFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 110, 40));

        CFechaIn.setBackground(new java.awt.Color(204, 204, 255));
        CFechaIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CFechaIn.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(CFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, 40));

        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Alta.png"))); // NOI18N
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 110, 60));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 100, 30));

        CBAlmuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Almuerzo" }));
        jPanel1.add(CBAlmuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 170, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Desayuno: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Almuerzo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 90, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Snack:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 70, 50));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Merienda:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cena:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 60, 40));

        CBSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Snack" }));
        jPanel1.add(CBSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 160, 40));

        CBDesayuno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Desayuno" }));
        CBDesayuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDesayunoActionPerformed(evt);
            }
        });
        jPanel1.add(CBDesayuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 40));

        CBMerienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Merienda" }));
        jPanel1.add(CBMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 170, 40));

        CBCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Cena" }));
        jPanel1.add(CBCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Lista de Dietas");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 2, 10, 630));

        tblDietas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "idPaciente", "Fecha Inicial", "Fecha Final", "Peso Inicial", "Fecha Final", "Terminada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDietas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDietas);
        if (tblDietas.getColumnModel().getColumnCount() > 0) {
            tblDietas.getColumnModel().getColumn(0).setResizable(false);
            tblDietas.getColumnModel().getColumn(1).setResizable(false);
            tblDietas.getColumnModel().getColumn(2).setResizable(false);
            tblDietas.getColumnModel().getColumn(3).setResizable(false);
            tblDietas.getColumnModel().getColumn(4).setResizable(false);
            tblDietas.getColumnModel().getColumn(5).setResizable(false);
            tblDietas.getColumnModel().getColumn(6).setResizable(false);
            tblDietas.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 660, 290));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        if (CBPacientes.getSelectedIndex() <=0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Paciente");
        }else if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LA casilla NOMBRE no puede quedar vacia.");
        }else if(CFechaIn.getDate() == null || CFechaFin.getDate() == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar las fechas.");
        }else if(!CFechaIn.getDate().before(CFechaFin.getDate())){
            JOptionPane.showMessageDialog(null, "La fecha de Inicio no puede ser mayor a la fecha Final.");
        }else if(CBDesayuno.getSelectedIndex() <= 0 || CBAlmuerzo.getSelectedIndex() <= 0 || CBMerienda.getSelectedIndex() <= 0 
                || CBCena.getSelectedIndex() <= 0 || CBSnack.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar las comidas.");
        }else{
            String nombre = txtNombre.getText();
            double pesoIn = Double.parseDouble(txtPesoIn.getText());
            Paciente paciente = pacientes.get(CBPacientes.getSelectedIndex()-1);
            System.out.println(paciente.getIdPaciente());
            Date fechaIncial = CFechaIn.getDate();
            Date fechaFinal = CFechaFin.getDate();
            LocalDate fechaIn = fechaIncial.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFin = fechaFinal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            double pesoFinal;
            boolean dietaTerminada = false;
            if (LocalDate.now().isEqual(fechaFin) || LocalDate.now().isAfter(fechaFin)){
                pesoFinal = pesoIn;
                dietaTerminada = true;
            }else{
                pesoFinal = 0;
            }
            Dieta dieta = new Dieta(nombre, paciente,fechaIn , fechaFin, pesoIn, pesoFinal, dietaTerminada);
            dietaData.altaDieta(dieta);
            
            //los datos de DietaComida
            
            DietaComida dietaComidaDesayuno = new DietaComida(comidas.get(CBDesayuno.getSelectedIndex()-1), dieta, Horario.DESAYUNO);
            DietaComida dietaComidaAlmuerzo = new DietaComida(comidas.get(CBAlmuerzo.getSelectedIndex()-1), dieta, Horario.ALMUERZO);
            DietaComida dietaComidaMerienda = new DietaComida(comidas.get(CBMerienda.getSelectedIndex()-1), dieta, Horario.MERIENDA);
            DietaComida dietaComidaCena = new DietaComida(comidas.get(CBCena.getSelectedIndex()-1), dieta, Horario.CENA);
            DietaComida dietaComidaSnack = new DietaComida(comidas.get(CBSnack.getSelectedIndex()-1), dieta, Horario.SNACK);
            
            dietaComidaData.altaDietaComida(dietaComidaDesayuno);
            dietaComidaData.altaDietaComida(dietaComidaAlmuerzo);
            dietaComidaData.altaDietaComida(dietaComidaMerienda);
            dietaComidaData.altaDietaComida(dietaComidaCena);
            dietaComidaData.altaDietaComida(dietaComidaSnack);
            
            limpiarDatos();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void CBPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPacientesActionPerformed
        if (CBPacientes.getSelectedIndex() > 0){
            double pesoA = pacientes.get(CBPacientes.getSelectedIndex()-1).getPesoActual();
            txtPesoIn.setText(String.valueOf(pesoA));
        }else{
            txtPesoIn.setText("");
        }
    }//GEN-LAST:event_CBPacientesActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
        txtPesoIn.setText("");
        CBPacientes.setSelectedIndex(0);
        CBDesayuno.setSelectedIndex(0);
        CBAlmuerzo.setSelectedIndex(0);
        CBMerienda.setSelectedIndex(0);
        CBCena.setSelectedIndex(0);
        CBSnack.setSelectedIndex(0);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void CBDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDesayunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBDesayunoActionPerformed

    private void cargarDatos(){
        pacientes.clear();
        pacientes.addAll(pacienteData.listarPacientes());
        CBPacientes.removeAllItems();
        CBPacientes.addItem("Seleccionar Paciente");
        for (Paciente p:pacientes){
            CBPacientes.addItem(p.toString());
        }
        comidas.clear();
        comidas.addAll(comidaData.listarComidas());
        CBDesayuno.removeAllItems();
        CBDesayuno.addItem("Seleccionar Desayuno");
        
        CBAlmuerzo.removeAllItems();
        CBAlmuerzo.addItem("Seleccionar Almuerzo");
        
        CBMerienda.removeAllItems();
        CBMerienda.addItem("Seleccionar Merienda");
        
        CBCena.removeAllItems();
        CBCena.addItem("Seleccionar Cena");
        
        CBSnack.removeAllItems();
        CBSnack.addItem("Seleccionar Snack");
        
        for(Comida c: comidas){
            CBDesayuno.addItem(c.toString());
            CBAlmuerzo.addItem(c.toString());
            CBMerienda.addItem(c.toString());
            CBCena.addItem(c.toString());
            CBSnack.addItem(c.toString());
        }
    }

    private void limpiarDatos(){
        txtNombre.setText("");
        txtPesoIn.setText("");
        CBPacientes.setSelectedIndex(0);
        CBDesayuno.setSelectedIndex(0);
        CBAlmuerzo.setSelectedIndex(0);
        CBMerienda.setSelectedIndex(0);
        CBCena.setSelectedIndex(0);
        CBSnack.setSelectedIndex(0);
    }
    
    private void cargarDietas(){
        dietas = new ArrayList<>();
        dietas.addAll(dietaData.listarDietas());
        for (Dieta d:dietas){
            modelo.addRow(new Object[]{d.getIdDieta(), d.getNombreDieta(), d.getPaciente().getIdPaciente(),
            d.getFechaInicial().toString(), d.getFechaFinal().toString(), d.getPesoInicial(), d.getPesoFinal(), d.isDietaTerminada()});
        }
    }
    
    private void armarTabla(){
        modelo.addColumn("id");
        modelo.addColumn("Nombre");
        modelo.addColumn("idPaciente");
        modelo.addColumn("Fecha Inicial");
        modelo.addColumn("Fecha Final");
        modelo.addColumn("Peso Inicial");
        modelo.addColumn("Peso Final");
        modelo.addColumn("terminada");
        tblDietas.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBAlmuerzo;
    private javax.swing.JComboBox<String> CBCena;
    private javax.swing.JComboBox<String> CBDesayuno;
    private javax.swing.JComboBox<String> CBMerienda;
    private javax.swing.JComboBox<String> CBPacientes;
    private javax.swing.JComboBox<String> CBSnack;
    private com.toedter.calendar.JDateChooser CFechaFin;
    private com.toedter.calendar.JDateChooser CFechaIn;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblDietas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPesoIn;
    // End of variables declaration//GEN-END:variables

    
}
